version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - auth-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      # KEYCLOAK_USER: admin
      # KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - auth-network

  web:
    build: ./app
    volumes:
        -  ./app/:/code
    ports:
        - "5000:5000"
    environment:
        PORT: 5000
        FLASK_DEBUG: 1
        AUTH_SERVER_PORT: 8080
    depends_on:
        - keycloak
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge